# Generated by Django 5.0.3 on 2024-04-04 03:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Equipo', '0008_alter_seccionequiposensor_fkseccionequipo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoEtapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=50)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Etapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('duracion_en_horas', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Duración en horas')),
                ('fkestadoEtapa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Proceso.estadoetapa')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LecturaEtapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Duración en horas')),
                ('fkESeccionEquipoSensor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Equipo.seccionequiposensor')),
                ('fkEtapa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Proceso.etapa')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Proceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('equipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='procesos', to='Equipo.equipo')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='etapa',
            name='fkProceso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Proceso.proceso'),
        ),
    ]
