# Generated by Django 5.0.3 on 2024-04-04 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proceso', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturaetapa',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Valor'),
        ),
    ]
