# Generated by Django 5.0.3 on 2024-05-06 01:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proceso', '0002_etapa_activo_historicaletapa_activo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalproceso',
            old_name='equipo',
            new_name='fkequipo',
        ),
        migrations.RenameField(
            model_name='proceso',
            old_name='equipo',
            new_name='fkequipo',
        ),
        migrations.RemoveField(
            model_name='etapa',
            name='fkestadoEtapa',
        ),
        migrations.RemoveField(
            model_name='historicaletapa',
            name='fkestadoEtapa',
        ),
        migrations.AlterField(
            model_name='etapa',
            name='fkProceso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Proceso.proceso', verbose_name='Proceso'),
        ),
        migrations.AlterField(
            model_name='historicaletapa',
            name='fkProceso',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Proceso.proceso', verbose_name='Proceso'),
        ),
    ]
