# Generated by Django 5.0.3 on 2024-09-09 02:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Equipo', '0006_alter_historicalseccionequipo_fkequipo_and_more'),
        ('Proceso', '0003_rename_equipo_historicalproceso_fkequipo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etapa',
            name='duracion_en_horas',
        ),
        migrations.RemoveField(
            model_name='historicaletapa',
            name='duracion_en_horas',
        ),
        migrations.AddField(
            model_name='etapa',
            name='duracion',
            field=models.DurationField(blank=True, null=True, verbose_name='Duración'),
        ),
        migrations.AddField(
            model_name='historicaletapa',
            name='duracion',
            field=models.DurationField(blank=True, null=True, verbose_name='Duración'),
        ),
        migrations.AlterField(
            model_name='etapa',
            name='nombre',
            field=models.CharField(default='Etapa', max_length=50, verbose_name='Etapa'),
        ),
        migrations.AlterField(
            model_name='historicaletapa',
            name='nombre',
            field=models.CharField(default='Etapa', max_length=50, verbose_name='Etapa'),
        ),
        migrations.AlterField(
            model_name='historicalproceso',
            name='fkequipo',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Equipo.equipo', verbose_name='Equipo'),
        ),
        migrations.AlterField(
            model_name='historicalproceso',
            name='nombre',
            field=models.CharField(max_length=50, verbose_name='Proceso'),
        ),
        migrations.AlterField(
            model_name='proceso',
            name='fkequipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='procesos', to='Equipo.equipo', verbose_name='Equipo'),
        ),
        migrations.AlterField(
            model_name='proceso',
            name='nombre',
            field=models.CharField(max_length=50, verbose_name='Proceso'),
        ),
    ]
