# Generated by Django 5.0.3 on 2024-04-05 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proceso', '0005_alter_historicallecturaetapa_valor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='etapa',
            name='nombre',
            field=models.CharField(default='Etapa', max_length=50),
        ),
        migrations.AddField(
            model_name='historicaletapa',
            name='nombre',
            field=models.CharField(default='Etapa', max_length=50),
        ),
    ]
