# Generated by Django 5.0.3 on 2024-09-14 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proceso', '0005_alter_etapa_fkproceso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etapa',
            name='activo',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='historicaletapa',
            name='activo',
            field=models.IntegerField(default=2),
        ),
    ]
