import requests

# Datos que deseas insertar en la API
data = [
    {"valor": 6.00, "fkEtapa": 1, "fkESeccionEquipoSensor": 1},
    {"valor": 6.00, "fkEtapa": 1, "fkESeccionEquipoSensor": 1},
    {"valor": 6.00, "fkEtapa": 1, "fkESeccionEquipoSensor": 1},
    {"valor": 5.90, "fkEtapa": 1, "fkESeccionEquipoSensor": 1},
    {"valor": 5.80, "fkEtapa": 1, "fkESeccionEquipoSensor": 1},
    {"valor": 5.5, "fkEtapa": 1, "fkESeccionEquipoSensor": 1},
    {"valor": 6.1, "fkEtapa": 1, "fkESeccionEquipoSensor": 1},
    {"valor": 6.00, "fkEtapa": 1, "fkESeccionEquipoSensor": 1},
    {"valor": 5.9, "fkEtapa": 1, "fkESeccionEquipoSensor": 1},
    {"valor": 5.8, "fkEtapa": 1, "fkESeccionEquipoSensor": 1},
    {"valor": 6.1, "fkEtapa": 1, "fkESeccionEquipoSensor": 1},
    {"valor": 6.1, "fkEtapa": 1, "fkESeccionEquipoSensor": 1},
    {"valor": 6.00, "fkEtapa": 1, "fkESeccionEquipoSensor": 1},
    {"valor": 5.9, "fkEtapa": 1, "fkESeccionEquipoSensor": 1},
    {"valor": 6.2, "fkEtapa": 1, "fkESeccionEquipoSensor": 1},
    {"valor": 6.1, "fkEtapa": 1, "fkESeccionEquipoSensor": 1},
    {"valor": 6.00, "fkEtapa": 1, "fkESeccionEquipoSensor": 1},
    {"valor": 5.5, "fkEtapa": 1, "fkESeccionEquipoSensor": 1},
    {"valor": 5.9, "fkEtapa": 1, "fkESeccionEquipoSensor": 1},
    {"valor": 5.9, "fkEtapa": 1, "fkESeccionEquipoSensor": 1},
    {"valor": 5.8, "fkEtapa": 1, "fkESeccionEquipoSensor": 1},
    {"valor": 5.8, "fkEtapa": 1, "fkESeccionEquipoSensor": 1},
    {"valor": 6.2, "fkEtapa": 1, "fkESeccionEquipoSensor": 1},
    {"valor": 6.00, "fkEtapa": 1, "fkESeccionEquipoSensor": 1},
    {"valor": 5.9, "fkEtapa": 1, "fkESeccionEquipoSensor": 1},
    {"valor": 5.8, "fkEtapa": 1, "fkESeccionEquipoSensor": 1},
    {"valor": 5.7, "fkEtapa": 1, "fkESeccionEquipoSensor": 1},
    {"valor": 5.6, "fkEtapa": 1, "fkESeccionEquipoSensor": 1},
    {"valor": 5.9, "fkEtapa": 1, "fkESeccionEquipoSensor": 1},
    {"valor": 6.1, "fkEtapa": 1, "fkESeccionEquipoSensor": 1},
    {"valor": 6.00, "fkEtapa": 1, "fkESeccionEquipoSensor": 1},
    {"valor": 5.8, "fkEtapa": 1, "fkESeccionEquipoSensor": 1},
    {"valor": 5.8, "fkEtapa": 1, "fkESeccionEquipoSensor": 1},
    {"valor": 6.00, "fkEtapa": 1, "fkESeccionEquipoSensor": 1},
    {"valor": 6.00, "fkEtapa": 1, "fkESeccionEquipoSensor": 1},
    {"valor": 5.8, "fkEtapa": 1, "fkESeccionEquipoSensor": 1},
    {"valor": 5.8, "fkEtapa": 1, "fkESeccionEquipoSensor": 1},
    {"valor": 5.8, "fkEtapa": 1, "fkESeccionEquipoSensor": 1},
    {"valor": 5.8, "fkEtapa": 1, "fkESeccionEquipoSensor": 1},
    {"valor": 5.8, "fkEtapa": 1, "fkESeccionEquipoSensor": 1},
    {"valor": 5.8, "fkEtapa": 1, "fkESeccionEquipoSensor": 1},
    {"valor": 5.9, "fkEtapa": 1, "fkESeccionEquipoSensor": 1},
    {"valor": 6.00, "fkEtapa": 1, "fkESeccionEquipoSensor": 1},
    {"valor": 6.2, "fkEtapa": 1, "fkESeccionEquipoSensor": 1},
    {"valor": 6.1, "fkEtapa": 1, "fkESeccionEquipoSensor": 1},
    {"valor": 5.9, "fkEtapa": 1, "fkESeccionEquipoSensor": 1},
    {"valor": 6.00, "fkEtapa": 1, "fkESeccionEquipoSensor": 1},
    {"valor": 5.9, "fkEtapa": 1, "fkESeccionEquipoSensor": 1},
    {"valor": 5.8, "fkEtapa": 1, "fkESeccionEquipoSensor": 1},
    {"valor": 6.1, "fkEtapa": 1, "fkESeccionEquipoSensor": 1},
    {"valor": 5.9, "fkEtapa": 1, "fkESeccionEquipoSensor": 1},
    {"valor": 6.2, "fkEtapa": 1, "fkESeccionEquipoSensor": 1},
    {"valor": 6.00, "fkEtapa": 1, "fkESeccionEquipoSensor": 1},
    {"valor": 5.6, "fkEtapa": 1, "fkESeccionEquipoSensor": 1},
    {"valor": 5.8, "fkEtapa": 1, "fkESeccionEquipoSensor": 1},
    {"valor": 6.00, "fkEtapa": 1, "fkESeccionEquipoSensor": 1},
    {"valor": 5.8, "fkEtapa": 1, "fkESeccionEquipoSensor": 1},
    {"valor": 5.8, "fkEtapa": 1, "fkESeccionEquipoSensor": 1},
    {"valor": 5.9, "fkEtapa": 1, "fkESeccionEquipoSensor": 1},
    {"valor": 5.8, "fkEtapa": 1, "fkESeccionEquipoSensor": 1},
    {"valor": 5.8, "fkEtapa": 1, "fkESeccionEquipoSensor": 1},
    {"valor": 5.8, "fkEtapa": 1, "fkESeccionEquipoSensor": 1},
    {"valor": 5.8, "fkEtapa": 1, "fkESeccionEquipoSensor": 1},
    {"valor": 5.8, "fkEtapa": 1, "fkESeccionEquipoSensor": 1},
    {"valor": 5.5, "fkEtapa": 1, "fkESeccionEquipoSensor": 1},
    {"valor": 5.5, "fkEtapa": 1, "fkESeccionEquipoSensor": 1},
    {"valor": 6.00, "fkEtapa": 1, "fkESeccionEquipoSensor": 1},
    {"valor": 6.00, "fkEtapa": 1, "fkESeccionEquipoSensor": 1},
    {"valor": 6.2, "fkEtapa": 1, "fkESeccionEquipoSensor": 1},
    {"valor": 5.6, "fkEtapa": 1, "fkESeccionEquipoSensor": 1},
    {"valor": 5.6, "fkEtapa": 1, "fkESeccionEquipoSensor": 1},
    {"valor": 5.5, "fkEtapa": 1, "fkESeccionEquipoSensor": 1},
    {"valor": 5.1, "fkEtapa": 1, "fkESeccionEquipoSensor": 1},
    {"valor": 5.1, "fkEtapa": 1, "fkESeccionEquipoSensor": 1},
    {"valor": 5.6, "fkEtapa": 1, "fkESeccionEquipoSensor": 1},
    {"valor": 5.6, "fkEtapa": 1, "fkESeccionEquipoSensor": 1},
    {"valor": 5.5, "fkEtapa": 1, "fkESeccionEquipoSensor": 1},
    {"valor": 5.1, "fkEtapa": 1, "fkESeccionEquipoSensor": 1},
    {"valor": 5.1, "fkEtapa": 1, "fkESeccionEquipoSensor": 1},
    {"valor": 5.2, "fkEtapa": 1, "fkESeccionEquipoSensor": 1},
    {"valor": 5.5, "fkEtapa": 1, "fkESeccionEquipoSensor": 1},
    {"valor": 5.5, "fkEtapa": 1, "fkESeccionEquipoSensor": 1},
    {"valor": 5.5, "fkEtapa": 1, "fkESeccionEquipoSensor": 1},
    {"valor": 5.1, "fkEtapa": 1, "fkESeccionEquipoSensor": 1},
    {"valor": 5.6, "fkEtapa": 1, "fkESeccionEquipoSensor": 1},
    {"valor": 5.6, "fkEtapa": 1, "fkESeccionEquipoSensor": 1},
    {"valor": 5.6, "fkEtapa": 1, "fkESeccionEquipoSensor": 1},
    {"valor": 5.6, "fkEtapa": 1, "fkESeccionEquipoSensor": 1},
    {"valor": 5.6, "fkEtapa": 1, "fkESeccionEquipoSensor": 1},
    {"valor": 5.6, "fkEtapa": 1, "fkESeccionEquipoSensor": 1},
    {"valor": 5.6, "fkEtapa": 1, "fkESeccionEquipoSensor": 1},
    {"valor": 5.6, "fkEtapa": 1, "fkESeccionEquipoSensor": 1},
    {"valor": 5.6, "fkEtapa": 1, "fkESeccionEquipoSensor": 1},
    {"valor": 5.5, "fkEtapa": 1, "fkESeccionEquipoSensor": 1},
    {"valor": 5.5, "fkEtapa": 1, "fkESeccionEquipoSensor": 1},
    {"valor": 5.6, "fkEtapa": 1, "fkESeccionEquipoSensor": 1},
    {"valor": 5.7, "fkEtapa": 1, "fkESeccionEquipoSensor": 1},
    {"valor": 5.1, "fkEtapa": 1, "fkESeccionEquipoSensor": 1},
    {"valor": 5.1, "fkEtapa": 1, "fkESeccionEquipoSensor": 1},
    {"valor": 5.5, "fkEtapa": 1, "fkESeccionEquipoSensor": 1},
    {"valor": 5.5, "fkEtapa": 1, "fkESeccionEquipoSensor": 1},
    {"valor": 5.5, "fkEtapa": 1, "fkESeccionEquipoSensor": 1},
    {"valor": 5.5, "fkEtapa": 1, "fkESeccionEquipoSensor": 1},
    {"valor": 5.5, "fkEtapa": 1, "fkESeccionEquipoSensor": 1},
    {"valor": 5.5, "fkEtapa": 1, "fkESeccionEquipoSensor": 1},
    {"valor": 5.5, "fkEtapa": 1, "fkESeccionEquipoSensor": 1},
    {"valor": 5.5, "fkEtapa": 1, "fkESeccionEquipoSensor": 1},
    {"valor": 5.6, "fkEtapa": 1, "fkESeccionEquipoSensor": 1},
    {"valor": 5.5, "fkEtapa": 1, "fkESeccionEquipoSensor": 1},
    {"valor": 5.6, "fkEtapa": 1, "fkESeccionEquipoSensor": 1},
    {"valor": 5.1, "fkEtapa": 1, "fkESeccionEquipoSensor": 1},
    {"valor": 5.1, "fkEtapa": 1, "fkESeccionEquipoSensor": 1},
    {"valor": 5.5, "fkEtapa": 1, "fkESeccionEquipoSensor": 1},
    {"valor": 5.1, "fkEtapa": 1, "fkESeccionEquipoSensor": 1},
    {"valor": 5.1, "fkEtapa": 1, "fkESeccionEquipoSensor": 1},
    {"valor": 5.1, "fkEtapa": 1, "fkESeccionEquipoSensor": 1},
    {"valor": 5.5, "fkEtapa": 1, "fkESeccionEquipoSensor": 1},
    {"valor": 5.6, "fkEtapa": 1, "fkESeccionEquipoSensor": 1},
    {"valor": 5.6, "fkEtapa": 1, "fkESeccionEquipoSensor": 1}
]

url = 'http://127.0.0.1:8000/api/v1/lectura/registro/'

token = '386fc05a3228b0f4fcab67cb9bca9c0d13cb7c77'

headers = {
    'Authorization': f'Token {token}',
    'Content-Type': 'application/json'
}

response = requests.post(url, json=data, headers=headers)

for item in data:
    response = requests.post(url, json=item, headers=headers)
    if response.status_code == 201:
        print(f"Los datos {item} fueron insertados correctamente en la API.")
    else:
        print(f"Hubo un error al insertar los datos {item} en la API:", response.text)
