# Generated by Django 5.0.3 on 2024-04-08 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Equipo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsensores',
            name='matricula',
            field=models.CharField(default='souhdofus', max_length=50),
        ),
        migrations.AddField(
            model_name='sensores',
            name='matricula',
            field=models.CharField(default='souhdofus', max_length=50),
        ),
    ]
