# Generated by Django 5.0.3 on 2024-04-03 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Equipo', '0001_initial'),
        ('Plantas', '0004_remove_planta_estado'),
        ('Producto', '0003_rename_valoresproductos_valoresproducto'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EquipoModel',
            new_name='Equipo',
        ),
    ]
