# Generated by Django 5.0.3 on 2024-04-27 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Equipo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsensores',
            name='matricula',
            field=models.CharField(default='VVFYGIYFCIUY', max_length=10),
        ),
        migrations.AlterField(
            model_name='seccionequiposensor',
            name='fksensor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sensor', to='Equipo.sensores'),
        ),
        migrations.AlterField(
            model_name='sensores',
            name='matricula',
            field=models.CharField(default='VVFYGIYFCIUY', max_length=10),
        ),
    ]
