# Generated by Django 5.0.3 on 2024-04-28 18:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Equipo', '0003_alter_equipo_usuario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuarioEq', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='seccionequiposensor',
            name='fkseccionEquipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secciones', to='Equipo.seccionequipo'),
        ),
        migrations.AlterField(
            model_name='seccionequiposensor',
            name='fksensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensor', to='Equipo.sensores'),
        ),
    ]
