# Generated by Django 5.0.3 on 2024-05-04 03:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Equipo', '0004_alter_equipo_usuario_and_more'),
        ('Plantas', '0001_initial'),
        ('Producto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='fkplanta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipos', to='Plantas.planta', verbose_name='Planta'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='fkproducto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipos', to='Producto.producto', verbose_name='Producto'),
        ),
        migrations.AlterField(
            model_name='historicalequipo',
            name='fkplanta',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Plantas.planta', verbose_name='Planta'),
        ),
        migrations.AlterField(
            model_name='historicalequipo',
            name='fkproducto',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Producto.producto', verbose_name='Producto'),
        ),
    ]
