# Generated by Django 5.0.3 on 2024-04-03 04:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Equipo', '0004_sensores_seccionequiposensor'),
        ('Plantas', '0004_remove_planta_estado'),
        ('Producto', '0003_rename_valoresproductos_valoresproducto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='fkplanta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipos', to='Plantas.planta'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='fkproducto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipos', to='Producto.producto'),
        ),
        migrations.AlterField(
            model_name='seccionequipo',
            name='fkequipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secciones', to='Equipo.equipo'),
        ),
        migrations.AlterField(
            model_name='seccionequiposensor',
            name='fkseccionEquipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sensores', to='Equipo.seccionequipo'),
        ),
        migrations.AlterField(
            model_name='seccionequiposensor',
            name='fksensor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secciones', to='Equipo.sensores'),
        ),
    ]
