# Generated by Django 5.0.3 on 2024-09-09 02:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Equipo', '0005_alter_equipo_fkplanta_alter_equipo_fkproducto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalseccionequipo',
            name='fkequipo',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Equipo.equipo', verbose_name='Equipo'),
        ),
        migrations.AlterField(
            model_name='seccionequipo',
            name='fkequipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secciones', to='Equipo.equipo', verbose_name='Equipo'),
        ),
    ]
