# Generated by Django 5.0.3 on 2024-09-14 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Equipo', '0006_alter_historicalseccionequipo_fkequipo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsensores',
            name='matricula',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='sensores',
            name='matricula',
            field=models.CharField(max_length=10),
        ),
    ]
