# Generated by Django 5.0.3 on 2024-04-04 03:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Equipo', '0007_sensores_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seccionequiposensor',
            name='fkseccionEquipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secciones', to='Equipo.seccionequipo'),
        ),
        migrations.AlterField(
            model_name='seccionequiposensor',
            name='fksensor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sensores', to='Equipo.sensores'),
        ),
    ]
