# Generated by Django 5.0.3 on 2024-05-04 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproducto',
            name='fografiaPex',
            field=models.TextField(blank='', default='', max_length=100, verbose_name='ProductoImg'),
        ),
        migrations.AddField(
            model_name='producto',
            name='fografiaPex',
            field=models.ImageField(blank='', default='', upload_to='producto/', verbose_name='ProductoImg'),
        ),
        migrations.AlterField(
            model_name='historicalproducto',
            name='created_at',
            field=models.DateField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name='historicalvaloresproducto',
            name='created_at',
            field=models.DateField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name='producto',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='valoresproducto',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
