# Generated by Django 5.0.3 on 2024-05-04 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0002_historicalproducto_fografiapex_producto_fografiapex_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproducto',
            name='fografiaPex',
            field=models.TextField(blank=True, default='', max_length=100, null=True, verbose_name='ProductoImg'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='fografiaPex',
            field=models.ImageField(blank=True, default='', null=True, upload_to='producto/', verbose_name='ProductoImg'),
        ),
    ]
