# Generated by Django 5.0.3 on 2024-04-02 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0002_remove_valoresproductos_productos_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ValoresProductos',
            new_name='ValoresProducto',
        ),
    ]
