# Generated by Django 5.0.3 on 2024-05-04 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0003_alter_historicalproducto_fografiapex_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproducto',
            name='etapa',
            field=models.CharField(default='Primera Fase', max_length=20),
        ),
        migrations.AddField(
            model_name='producto',
            name='etapa',
            field=models.CharField(default='Primera Fase', max_length=20),
        ),
    ]
