# Generated by Django 5.0.3 on 2024-04-10 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Organizacion', '0002_historicalorganizacion'),
        ('Plantas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalplanta',
            name='organizacion',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Organizacion.organizacion'),
        ),
        migrations.AddField(
            model_name='planta',
            name='organizacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Organizacion.organizacion'),
        ),
    ]
