# Generated by Django 5.0.3 on 2024-04-02 02:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Plantas', '0002_estado_planta_calle_alter_planta_estado_municipio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planta',
            name='estado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estado', to='Plantas.estado'),
        ),
        migrations.AlterField(
            model_name='planta',
            name='municipio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='municipio', to='Plantas.municipio'),
        ),
    ]
