# Generated by Django 5.0.3 on 2024-04-19 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Plantas', '0003_alter_estado_nombre_alter_historicalestado_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmunicipio',
            name='nombre',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='historicalplanta',
            name='nombre',
            field=models.CharField(db_index=True, default='Planta', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='municipio',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='planta',
            name='nombre',
            field=models.CharField(default='Planta', max_length=50, null=True, unique=True),
        ),
    ]
