# Generated by Django 5.0.3 on 2024-04-02 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Plantas', '0003_alter_planta_estado_alter_planta_municipio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planta',
            name='estado',
        ),
    ]
