# Generated by Django 5.0.3 on 2024-04-19 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Plantas', '0004_alter_historicalmunicipio_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalplanta',
            name='nombre',
            field=models.CharField(db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='planta',
            name='nombre',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
