# Generated by Django 5.0.3 on 2024-04-10 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Organizacion', '0002_historicalorganizacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorganizacion',
            name='descrpcion',
            field=models.TextField(default='Empresa  de Acuicultura ', max_length=250),
        ),
        migrations.AddField(
            model_name='organizacion',
            name='descrpcion',
            field=models.TextField(default='Empresa  de Acuicultura ', max_length=250),
        ),
    ]
