# Generated by Django 5.0.3 on 2024-05-03 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Organizacion', '0002_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorganizacion',
            name='logo',
            field=models.TextField(blank='', default='', max_length=100),
        ),
        migrations.AddField(
            model_name='organizacion',
            name='logo',
            field=models.ImageField(blank='', default='', upload_to='logo/'),
        ),
    ]
