# Generated by Django 5.0.3 on 2024-04-10 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Organizacion', '0003_historicalorganizacion_descrpcion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalorganizacion',
            old_name='descrpcion',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='organizacion',
            old_name='descrpcion',
            new_name='descripcion',
        ),
    ]
