# Generated by Django 5.0.3 on 2024-05-03 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Organizacion', '0004_alter_historicalorganizacion_fkusuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalorganizacion',
            name='matricula',
            field=models.CharField(default='afw3fdfs', max_length=8),
        ),
        migrations.AlterField(
            model_name='organizacion',
            name='matricula',
            field=models.CharField(default='afw3fdfs', max_length=8),
        ),
    ]
