# Generated by Django 5.0.3 on 2024-04-19 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Organizacion', '0004_rename_descrpcion_historicalorganizacion_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorganizacion',
            name='matricula',
            field=models.TextField(default='afw3fdfs', max_length=8),
        ),
        migrations.AddField(
            model_name='organizacion',
            name='matricula',
            field=models.TextField(default='afw3fdfs', max_length=8),
        ),
        migrations.AlterField(
            model_name='historicalorganizacion',
            name='descripcion',
            field=models.TextField(default='Empresa de Acuicultura ', max_length=250),
        ),
        migrations.AlterField(
            model_name='organizacion',
            name='descripcion',
            field=models.TextField(default='Empresa de Acuicultura ', max_length=250),
        ),
    ]
