# Generated by Django 5.0.3 on 2024-05-03 17:14

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Organizacion', '0005_alter_historicalorganizacion_matricula_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorganizacion',
            name='con_Telefono',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, default='9999999', max_length=128, null=True, region=None, verbose_name='Telefono'),
        ),
        migrations.AddField(
            model_name='historicalorganizacion',
            name='con_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo'),
        ),
        migrations.AddField(
            model_name='organizacion',
            name='con_Telefono',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, default='9999999', max_length=128, null=True, region=None, verbose_name='Telefono'),
        ),
        migrations.AddField(
            model_name='organizacion',
            name='con_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo'),
        ),
    ]
